[build]
  base = "/"
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200